import numpy as np
print(np.__version__)
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
a = np.array(10)
print(a)
print(a.ndim)
b = np.array([1, 2, 3])
print(b)
print(b.ndim)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)
print(a.ndim)
print(a.shape)
